repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: no-commit-to-branch
  - id: check-docstring-first
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: requirements-txt-fixer

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
    args: [--profile, black, --filter-files]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]

- repo: https://github.com/DanielNoord/pydocstringformatter
  rev: v0.6.2
  hooks:
  - id: pydocstringformatter
