[tool.black]
line-length = 80
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
line_length = 80
profile = "black"
py_version = 38

[tool.pylint]
init-hook = 'import sys; sys.path.append(".")'
py-version = [3, 8]
max-line-length = 80
good-names = [
    "main",
]
disable = [
    "import-outside-toplevel",
    "duplicate-code",
    ]
check-quote-consistency = true
ignore-imports = false
notes = [
    "TODO",
    "FIXME"
]
logging-modules = [
    "logging",
]
